apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-PV_NAME_PLACEHOLDER
  labels:
    app: minio
    node: NODE_PLACEHOLDER
spec:
  capacity:
    storage: STORAGE_SIZE_PLACEHOLDER
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-local
  hostPath:
    path: /mnt/minio
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODE_PLACEHOLDER
