apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: NAMESPACE_PLACEHOLDER
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: minio-local
  resources:
    requests:
      storage: STORAGE_SIZE_PLACEHOLDER
  volumeName: minio-data-PV_NAME_PLACEHOLDER
