apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: minio
    node: NODE_PLACEHOLDER
    component: console
spec:
  type: LoadBalancer
  ports:
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: minio
