#!/bin/bash

###############################################################################
# Quick Install: Control Plane
#
# This script automates the installation of a MyNodeOne Control Plane.
# It sets up defaults and runs the main installer in unattended mode.
#
# Usage:
#   sudo ./scripts/install-control-plane.sh [OPTIONS]
#
# Options:
#   --cluster-name <name>    Name of the cluster (default: mynodeone)
#   --domain <domain>        Local domain (default: mynodeone)
#   --email <email>          Email for SSL (optional)
###############################################################################

set -e

# Default values
CLUSTER_NAME="mynodeone"
CLUSTER_DOMAIN="mynodeone"
SSL_EMAIL=""
NODE_NAME="$(hostname)"
NODE_LOCATION="home"

FORCE_INSTALL=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --cluster-name)
            CLUSTER_NAME="$2"
            shift 2
            ;;
        --domain)
            CLUSTER_DOMAIN="$2"
            shift 2
            ;;
        --email)
            SSL_EMAIL="$2"
            shift 2
            ;;
        --force)
            FORCE_INSTALL=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Check root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root (sudo)"
    exit 1
fi

# Detect user
ACTUAL_USER="${SUDO_USER:-$(whoami)}"
if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    ACTUAL_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    ACTUAL_HOME="$HOME"
fi

# GUARDRAIL: Check for existing installation
if [ -f "$ACTUAL_HOME/.mynodeone/config.env" ] && [ "$FORCE_INSTALL" = false ]; then
    echo "❌ ERROR: MyNodeOne is already installed!"
    echo "Running this script will ERASE your existing installation in unattended mode."
    echo
    echo "To proceed with reinstall (DATA LOSS), use: --force"
    exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MyNodeOne Control Plane - Quick Install"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Cluster Name:   $CLUSTER_NAME"
echo "Cluster Domain: $CLUSTER_DOMAIN.local"
echo "Node Name:      $NODE_NAME"
echo "User:           $ACTUAL_USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# Create config directory with correct ownership
mkdir -p "$ACTUAL_HOME/.mynodeone"
chown "$ACTUAL_USER:$ACTUAL_USER" "$ACTUAL_HOME/.mynodeone"

# Create configuration file
CONFIG_FILE="$ACTUAL_HOME/.mynodeone/config.env"
echo "Creating configuration at $CONFIG_FILE..."

# Get Tailscale IP if available
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo "")

cat > "$CONFIG_FILE" <<EOF
# MyNodeOne Configuration
# Generated by install-control-plane.sh on $(date)

# Cluster
CLUSTER_NAME="$CLUSTER_NAME"
CLUSTER_DOMAIN="$CLUSTER_DOMAIN"
NODE_NAME="$NODE_NAME"
NODE_TYPE="control-plane"
NODE_LOCATION="$NODE_LOCATION"

# Network
TAILSCALE_IP="$TAILSCALE_IP"

# Features (Enable everything by default for 'one click' experience)
NUM_VPS="0"
ENABLE_LLM="true"
ENABLE_DATABASES="true"
HAS_GPU="false"

# Storage (Auto-select Longhorn)
DISK_OPTION="1"
EOF

# Check for GPU and offer to install drivers
if lspci | grep -i nvidia &> /dev/null; then
    echo "HAS_GPU=\"true\"" >> "$CONFIG_FILE"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  NVIDIA GPU Detected"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    lspci | grep -i nvidia | head -3
    echo ""
fi

chown "$ACTUAL_USER:$ACTUAL_USER" "$CONFIG_FILE"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GPU Setup (before K3s installation)
if lspci | grep -i nvidia &> /dev/null; then
    if [ -f "$SCRIPT_DIR/lib/gpu-setup.sh" ]; then
        # Skip if driver already installed and working
        if ! command -v nvidia-smi &>/dev/null || ! nvidia-smi &>/dev/null; then
            echo ""
            # Interactive GPU setup - will prompt user
            bash "$SCRIPT_DIR/lib/gpu-setup.sh" --no-plugin
            GPU_EXIT_CODE=$?
            
            if [ $GPU_EXIT_CODE -eq 2 ]; then
                echo ""
                echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                echo "  REBOOT REQUIRED"
                echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                echo "  NVIDIA driver was installed. Please reboot and run this script again:"
                echo ""
                echo "    sudo reboot"
                echo ""
                echo "  After reboot:"
                echo "    sudo ./scripts/install-control-plane.sh"
                echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                exit 0
            fi
        else
            echo "✓ NVIDIA driver already installed and working"
        fi
    fi
fi

# Run main installer in UNATTENDED mode
echo "Starting installation..."
export UNATTENDED=1

# Run the main script
bash "$SCRIPT_DIR/mynodeone"

# Post-install: Deploy NVIDIA Device Plugin if GPU is present
if lspci | grep -i nvidia &> /dev/null; then
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
        echo ""
        echo "Deploying NVIDIA Device Plugin to Kubernetes..."
        
        # Try local manifest first (works offline), then remote
        LOCAL_MANIFEST="$SCRIPT_DIR/../manifests/gpu/nvidia-device-plugin.yaml"
        REMOTE_MANIFEST="https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.5/nvidia-device-plugin.yml"
        
        if [ -f "$LOCAL_MANIFEST" ]; then
            kubectl apply -f "$LOCAL_MANIFEST" 2>/dev/null || true
            echo "✓ NVIDIA Device Plugin deployed (from local manifest)"
        elif curl -s --connect-timeout 5 "$REMOTE_MANIFEST" &>/dev/null; then
            kubectl apply -f "$REMOTE_MANIFEST" 2>/dev/null || true
            echo "✓ NVIDIA Device Plugin deployed (from remote)"
        else
            echo "⚠ Could not deploy NVIDIA Device Plugin (no network)"
            echo "  Deploy manually later with:"
            echo "  kubectl apply -f manifests/gpu/nvidia-device-plugin.yaml"
        fi
        
        echo ""
        echo "GPU resources will be available as 'nvidia.com/gpu' in pod specs"
        echo "Each GPU node exposes its GPUs independently to the cluster scheduler"
    fi
fi

