#!/bin/bash

###############################################################################
# Quick Install: Control Plane
#
# This script automates the installation of a MyNodeOne Control Plane.
# It sets up defaults and runs the main installer in unattended mode.
#
# Usage:
#   sudo ./scripts/install-control-plane.sh [OPTIONS]
#
# Options:
#   --cluster-name <name>    Name of the cluster (default: mynodeone)
#   --domain <domain>        Local domain (default: mynodeone)
#   --email <email>          Email for SSL (optional)
###############################################################################

set -e

# Default values
CLUSTER_NAME="mynodeone"
CLUSTER_DOMAIN="mynodeone"
SSL_EMAIL=""
NODE_NAME="$(hostname)"
NODE_LOCATION="home"

FORCE_INSTALL=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --cluster-name)
            CLUSTER_NAME="$2"
            shift 2
            ;;
        --domain)
            CLUSTER_DOMAIN="$2"
            shift 2
            ;;
        --email)
            SSL_EMAIL="$2"
            shift 2
            ;;
        --force)
            FORCE_INSTALL=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Check root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root (sudo)"
    exit 1
fi

# Detect user
ACTUAL_USER="${SUDO_USER:-$(whoami)}"
if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    ACTUAL_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    ACTUAL_HOME="$HOME"
fi

# GUARDRAIL: Check for existing installation
if [ -f "$ACTUAL_HOME/.mynodeone/config.env" ] && [ "$FORCE_INSTALL" = false ]; then
    echo "❌ ERROR: MyNodeOne is already installed!"
    echo "Running this script will ERASE your existing installation in unattended mode."
    echo
    echo "To proceed with reinstall (DATA LOSS), use: --force"
    exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MyNodeOne Control Plane - Quick Install"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Cluster Name:   $CLUSTER_NAME"
echo "Cluster Domain: $CLUSTER_DOMAIN.local"
echo "Node Name:      $NODE_NAME"
echo "User:           $ACTUAL_USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# Create config directory with correct ownership
mkdir -p "$ACTUAL_HOME/.mynodeone"
chown "$ACTUAL_USER:$ACTUAL_USER" "$ACTUAL_HOME/.mynodeone"

# Create configuration file
CONFIG_FILE="$ACTUAL_HOME/.mynodeone/config.env"
echo "Creating configuration at $CONFIG_FILE..."

# Get Tailscale IP if available
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo "")

cat > "$CONFIG_FILE" <<EOF
# MyNodeOne Configuration
# Generated by install-control-plane.sh on $(date)

# Cluster
CLUSTER_NAME="$CLUSTER_NAME"
CLUSTER_DOMAIN="$CLUSTER_DOMAIN"
NODE_NAME="$NODE_NAME"
NODE_TYPE="control-plane"
NODE_LOCATION="$NODE_LOCATION"

# Network
TAILSCALE_IP="$TAILSCALE_IP"

# Features (Enable everything by default for 'one click' experience)
NUM_VPS="0"
ENABLE_LLM="true"
ENABLE_DATABASES="true"
HAS_GPU="false"

# Storage (Auto-select Longhorn)
DISK_OPTION="1"
EOF

# Check for GPU and offer to install drivers
if lspci | grep -i nvidia &> /dev/null; then
    echo "HAS_GPU=\"true\"" >> "$CONFIG_FILE"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  NVIDIA GPU Detected"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    lspci | grep -i nvidia | head -3
    echo ""
fi

chown "$ACTUAL_USER:$ACTUAL_USER" "$CONFIG_FILE"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GPU Setup (before K3s installation) - Install toolkit if needed
if lspci | grep -i nvidia &> /dev/null; then
    if [ -f "$SCRIPT_DIR/lib/gpu-setup.sh" ]; then
        # Check if driver is installed
        if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
            echo "✓ NVIDIA driver already installed and working"
            
            # Install Container Toolkit if not present
            if ! command -v nvidia-ctk &>/dev/null; then
                echo "  → Installing NVIDIA Container Toolkit..."
                bash "$SCRIPT_DIR/lib/gpu-setup.sh" --toolkit-only --no-plugin
            else
                echo "✓ NVIDIA Container Toolkit already installed"
            fi
            
            # Mark GPU as ready for post-install configuration
            export GPU_READY=true
        else
            echo ""
            # Interactive GPU setup - will prompt user
            bash "$SCRIPT_DIR/lib/gpu-setup.sh" --no-plugin
            GPU_EXIT_CODE=$?
            
            if [ $GPU_EXIT_CODE -eq 2 ]; then
                echo ""
                echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                echo "  REBOOT REQUIRED"
                echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                echo "  NVIDIA driver was installed. Please reboot and run this script again:"
                echo ""
                echo "    sudo reboot"
                echo ""
                echo "  After reboot:"
                echo "    sudo ./scripts/install-control-plane.sh"
                echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                exit 0
            fi
            export GPU_READY=true
        fi
    fi
fi

# Run main installer in UNATTENDED mode
echo "Starting installation..."
export UNATTENDED=1

# Run the main script
bash "$SCRIPT_DIR/mynodeone"

# Post-install: Configure GPU support for K3s (after K3s is installed)
if lspci | grep -i nvidia &> /dev/null; then
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  Configuring GPU Support for Kubernetes"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        
        # Step 1: Create runc symlink (K3s bundles runc in non-standard location)
        echo "→ Setting up runc symlink..."
        if [ ! -f /usr/bin/runc ]; then
            K3S_RUNC="/var/lib/rancher/k3s/data/current/bin/runc"
            if [ -f "$K3S_RUNC" ]; then
                ln -sf "$K3S_RUNC" /usr/bin/runc
                echo "  ✓ Created runc symlink"
            else
                # Try to find runc in K3s data directory
                K3S_RUNC=$(find /var/lib/rancher/k3s/data -name "runc" -type f 2>/dev/null | head -1)
                if [ -n "$K3S_RUNC" ]; then
                    ln -sf "$K3S_RUNC" /usr/bin/runc
                    echo "  ✓ Created runc symlink from $K3S_RUNC"
                else
                    echo "  ⚠ Could not find K3s runc binary"
                fi
            fi
        else
            echo "  ✓ runc symlink already exists"
        fi
        
        # Step 2: Create K3s containerd config template for GPU
        echo "→ Configuring K3s containerd for NVIDIA runtime..."
        K3S_CONTAINERD_DIR="/var/lib/rancher/k3s/agent/etc/containerd"
        mkdir -p "$K3S_CONTAINERD_DIR"
        
        # Always recreate the config to ensure it's correct
        cat > "$K3S_CONTAINERD_DIR/config.toml.tmpl" <<'CONTAINERD_EOF'
# This template extends the default K3s containerd config
# CRITICAL: {{ template "base" . }} preserves CNI networking
{{ template "base" . }}

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia"]
  privileged_without_host_devices = false
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia".options]
  BinaryName = "/usr/bin/nvidia-container-runtime"
CONTAINERD_EOF
        echo "  ✓ Created K3s containerd GPU config"
        
        # Step 3: Restart K3s to pick up the new containerd config
        echo "→ Restarting K3s to apply GPU configuration..."
        systemctl restart k3s
        
        # Wait for K3s to be ready
        echo "  Waiting for K3s to be ready..."
        sleep 10
        WAIT_COUNT=0
        while ! kubectl get nodes &>/dev/null; do
            sleep 5
            WAIT_COUNT=$((WAIT_COUNT + 1))
            if [ $WAIT_COUNT -gt 24 ]; then
                echo "  ⚠ K3s taking longer than expected to restart"
                break
            fi
            echo -n "."
        done
        echo ""
        echo "  ✓ K3s restarted with GPU support"
        
        # Step 4: Deploy NVIDIA Device Plugin
        echo "→ Deploying NVIDIA Device Plugin..."
        LOCAL_MANIFEST="$SCRIPT_DIR/../manifests/gpu/nvidia-device-plugin.yaml"
        REMOTE_MANIFEST="https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.5/nvidia-device-plugin.yml"
        
        if [ -f "$LOCAL_MANIFEST" ]; then
            kubectl apply -f "$LOCAL_MANIFEST" 2>/dev/null || true
            echo "  ✓ NVIDIA Device Plugin deployed (from local manifest)"
        elif curl -s --connect-timeout 5 "$REMOTE_MANIFEST" &>/dev/null; then
            kubectl apply -f "$REMOTE_MANIFEST" 2>/dev/null || true
            echo "  ✓ NVIDIA Device Plugin deployed (from remote)"
        else
            echo "  ⚠ Could not deploy NVIDIA Device Plugin (no network)"
            echo "    Deploy manually later with:"
            echo "    kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.5/nvidia-device-plugin.yml"
        fi
        
        # Step 5: Wait for device plugin to be ready and verify GPU
        echo "→ Waiting for GPU to be detected..."
        sleep 30
        
        # Check if GPU is visible
        GPU_COUNT=$(kubectl get nodes -o jsonpath='{.items[*].status.allocatable.nvidia\.com/gpu}' 2>/dev/null || echo "")
        if [ -n "$GPU_COUNT" ] && [ "$GPU_COUNT" != "0" ]; then
            echo "  ✓ GPU detected: $GPU_COUNT GPU(s) available"
        else
            echo "  ⚠ GPU not yet visible - device plugin may still be starting"
            echo "    Check with: kubectl get nodes -o jsonpath='{.items[*].status.allocatable}' | grep nvidia"
        fi
        
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  GPU Setup Complete"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "GPU resources will be available as 'nvidia.com/gpu' in pod specs"
        echo ""
    fi
fi

